# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: 构建kanban_app前端
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [master]
# CI enviroment settings
env:
  STATE_RELEASE_VERSION: "1.0" # chrome version
  TAG_NAME: "kanban"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    steps:
      - uses: actions/checkout@v2
      # - uses: bahmutov/npm-install@v1
      #   with:
      #     working-directory: .
      - name: install npm
        run: apt-get install npm -y
      
      - name: install yarn
        run: npm install -g yarn
      # here are some step followed , each step must have `uses` or `run` key , for CI to run
      # other key like `name`,`with`,`env` is optional
      - name: yarn
        run: yarn
      - name: build ----
        run: quasar build -m electron
      - name: show ----
        run: ls -a
      - name: Output Docker info
        run: docker info
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # #版本号第一位不允许空格
      # - name: Push to Docker Hub
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     tags: "includeno/${{env.TAG_NAME}}:latest,includeno/${{env.TAG_NAME}}:1.0"
      #     push: true
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"
    
   