# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: 构建kanban app 前端
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [main]
# CI enviroment settings
env:
  STATE_RELEASE_VERSION: "1.0" # chrome version
  TAG_NAME: "kanban"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest # use latest ubuntu to run the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # here are some step followed , each step must have `uses` or `run` key , for CI to run
      # other key like `name`,`with`,`env` is optional
      
      - name: Output Docker info
        run: docker info
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #版本号第一位不允许空格
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "includeno/${{env.TAG_NAME}}:latest,includeno/${{env.TAG_NAME}}:${{env.STATE_RELEASE_VERSION}}"
          push: true
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"
    
   